// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7znXcX9TohjrByWHBR8OjpMr2qsDETeg',
    appId: '1:963296147693:web:your-web-app-id',
    messagingSenderId: '963296147693',
    projectId: 'ezzat-flutter-task',
    authDomain: 'ezzat-flutter-task.firebaseapp.com',
    storageBucket: 'ezzat-flutter-task.firebasestorage.app',
    measurementId: 'G-XXXXXXXXXX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7znXcX9TohjrByWHBR8OjpMr2qsDETeg',
    appId: '1:963296147693:android:115d107d6a109c82e974e4',
    messagingSenderId: '963296147693',
    projectId: 'ezzat-flutter-task',
    storageBucket: 'ezzat-flutter-task.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7znXcX9TohjrByWHBR8OjpMr2qsDETeg',
    appId: '1:963296147693:ios:your-ios-app-id',
    messagingSenderId: '963296147693',
    projectId: 'ezzat-flutter-task',
    storageBucket: 'ezzat-flutter-task.firebasestorage.app',
    iosBundleId: 'com.example.fluttertask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7znXcX9TohjrByWHBR8OjpMr2qsDETeg',
    appId: '1:963296147693:ios:your-macos-app-id',
    messagingSenderId: '963296147693',
    projectId: 'ezzat-flutter-task',
    storageBucket: 'ezzat-flutter-task.firebasestorage.app',
    iosBundleId: 'com.example.fluttertask',
  );
}
